### ISSUE TITLE
Tester og litt mer norsk dokumentasjon

### ISSUE THREAD

**Issue by Kyrremann** [navikt/muckscan#2]
Kunne vi fått noen tester, eller i det minste output som viser hva som skjer hvis den finner feil, og hva som skjer hvis alt er bra?

Kunne trengt litt mer dokumentasjon, og gjerne på norsk.

**Comment by kimtore** [comment]
Eksempel-output kan vi fikse. Hva slags type dokumentasjon trenger du? Hvis du vil ha det på norsk synes jeg du kan komme med noen slående argumenter for det, særlig når den fagterminologien og dokumentasjonen vi bruker innen IT finnes primært på engelsk.

**Comment by Kyrremann** [comment]
Dokumentasjon var mer rettet mot hva slags output man kan forvente seg av en kjøring. Kunne kanskje også stått litt om hva vi har endret eller lagt til for å gjøre det mer NAV-spesifikt.

To grunner til at jeg liker å ha dokumentasjonen på norsk, føler ofte at vi er flinkere til å utdype og forklare oss på norsk, enn engelsk. Nummer to er at vi er en statlig organ som skal legge til rette for norsk. Unntaket finnes det jo, for eksempel er det jo unødvendig å oversette en ren fork.
